### ISSUE TITLE
README -> README.md

### ISSUE THREAD

**Issue by sarum9in** [BasicWolf/archived-kaylee#1]
This will make documentation render (not only as plain text).

**Comment by BasicWolf** [comment]
Thank you for suggestion, sarum9in. At the beginning it was README.rst, so that it could be rendered by GitHub from reStructuredText format (the same one used in Sphinx documentation engine), but it looked a bit ugly to me, like good old "README" just looks nicer than "README.xxx". I was hoping that GitHub would recognize reStructuredText or there would be a way to "tell" GitHub which rendering engine to use..

**Comment by sarum9in** [comment]
What do you think about using symlinks? The only problem with README's suffix I see: it is non-standard for users that read it directly (using vim, after git-clone, for instance). But it that case, if README(->README.rst) is provided, it is OK. When somebody uses github's interface, he does not look into README directly, he will definitely read README rendered by github.

See one of my repositories with this idea implemented: https://github.com/sarum9in/yandex_contest_invoker_debian .

**Comment by BasicWolf** [comment]
Whoa! Thank you very much, haven't thought of it in that way. I'll add a symlink ASAP.

**Comment by sarum9in** [comment]
You are welcome :)
